name: uhsaf
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.2+2
  share: ^0.6.5+4
  path: ^1.7.0
  path_provider: ^1.6.27
  csv: ^4.1.0
  theme_provider: ^0.4.0+1
  get: ^3.24.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.8.1
  change_app_package_name: ^0.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DINPro
      fonts:
        - asset: assets/fonts/DINPro-Black.otf
        - asset: assets/fonts/DINPro-Bold.otf
        - asset: assets/fonts/DINPro-Light.otf
        - asset: assets/fonts/DINPro-Medium.otf
        - asset: assets/fonts/DINPro-Regular.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/icon-ios.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
  fill: true
